export const UPDATE_TOPIC = 'UPDATE_TOPIC'
export const UPDATE_TOPICS = 'UPDATE_TOPICS'
export const GET_TOPIC_ING = 'GET_TOPIC_ING'
export const GET_TOPIC_ERROR = 'GET_TOPIC_ERROR'

export const GET_TOPIC_LIST_ING = 'GET_TOPIC_LIST_ING'
export const GET_TOPIC_LIST_SUCCESS = 'GET_TOPIC_LIST_SUCCESS'
export const GET_TOPIC_LIST_ERROR = 'GET_TOPIC_LIST_ERROR'

export const GET_NODES_ING = 'GET_NODES_ING'
export const GET_NODES_SUCCESS = 'GET_NODES_SUCCESS'
export const GET_NODES_ERROR = 'GET_NODES_ERROR'

export const GET_REPLIES = 'GET_REPLIES'